api = "0.2"

[buildpack]
id = "google.ruby.bundle"
version = "0.9.0"
name = "Ruby - Bundle"

#添加一个作用于的stack,Stacks that the buildpack will work with
[[stacks]]
id = "google"
[[stacks]]
id = "google.ruby25"

[[stacks]]
id = "google.ruby26"

[[stacks]]
id = "google.ruby27"
