description = "Builder for the GCF Ruby 2.6 runtime"

[[buildpacks]]
  id = "google.ruby.functions-framework"
  uri = "ruby/functions_framework.tgz"

[[buildpacks]]
  id = "google.ruby.bundle"
  uri = "ruby/bundle.tgz"

#[[buildpacks]]
#  id = "google.utils.archive-source"
#  uri = "archive_source.tgz"

[[buildpacks]]
  id = "google.utils.label"
  uri = "label.tgz"

[[order]]

#  [[order.group]]
#    id = "google.utils.archive-source"
#调整一下顺序
  [[order.group]]
    id = "google.ruby.bundle"

  [[order.group]]
    id = "google.ruby.functions-framework"



  [[order.group]]
    id = "google.utils.label"

#[stack]
#  id = "google.ruby26"
#  build-image = "gcr.io/gae-runtimes/buildpacks/ruby26/build"
#  run-image = "gcr.io/gae-runtimes/buildpacks/ruby26/run"

[stack]
  id = "google"
  build-image = "penghuima/buildpacks-ruby26-build:v1"
  run-image = "penghuima/buildpacks-ruby26-run:v1"

[lifecycle]
  version = "0.11.1"
